#!/usr/bin/env bash

# Strip exif data from photos
# Uses the convert program from ImageMagick

set -e

if ! convert_location="$(type -p "convertp")" || [ -z "$convert_location" ]; then
  echo "ImageMagick not installed, exiting"
  exit 1
fi

shopt -s nullglob
shopt -s nocaseglob

for photo in *.{jpg,jpeg,png} ; do
  echo "Processing $photo"

  filename=$(basename "$photo")
  extension="${filename##*.}"
  filename="${filename%.*}"

  convert $photo -strip "$filename-no-exif.$extension"
done
